/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_francisco;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Francisco Santos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_CrearCuenta = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_contraseña = new javax.swing.JPasswordField();
        tf_nombre = new javax.swing.JTextField();
        tf_username = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        bt_crearCuenta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jd_login = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_usernameLogin = new javax.swing.JTextField();
        tf_password = new javax.swing.JPasswordField();
        bt_login = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jd_menu = new javax.swing.JDialog();
        bt_usuarios = new javax.swing.JLabel();
        bt_canciones = new javax.swing.JLabel();
        bt_albums = new javax.swing.JLabel();
        bt_guardarUsuarios = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jd_usuarios = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_listarUsuarios = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_eliminarUsuarios = new javax.swing.JList<>();
        bt_eliminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jd_Canciones = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cb_albums = new javax.swing.JComboBox<>();
        sp_duracion = new javax.swing.JSpinner();
        tf_nombreCancion = new javax.swing.JTextField();
        tf_genero = new javax.swing.JTextField();
        tf_artistaCancion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        bt_crearCancion = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jd_albums = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tf_nombreAlbum = new javax.swing.JTextField();
        tf_artistaAlbum = new javax.swing.JTextField();
        bt_crearAlbum = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_listarAlbums = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_eliminarAlbums = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jl_CrearCuenta = new javax.swing.JLabel();
        jl_login = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel1.setText("Nombre");

        jLabel2.setText("Username");

        jLabel3.setText("Edad");

        jLabel4.setText("Contraseña");

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(14, 14, null, 1));

        jLabel5.setText("años");

        bt_crearCuenta.setText("Guardar");
        bt_crearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearCuentaMouseClicked(evt);
            }
        });

        jLabel6.setText("Crear Cuenta");

        javax.swing.GroupLayout jd_CrearCuentaLayout = new javax.swing.GroupLayout(jd_CrearCuenta.getContentPane());
        jd_CrearCuenta.getContentPane().setLayout(jd_CrearCuentaLayout);
        jd_CrearCuentaLayout.setHorizontalGroup(
            jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearCuentaLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(bt_crearCuenta)
                .addGap(142, 142, 142))
            .addGroup(jd_CrearCuentaLayout.createSequentialGroup()
                .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearCuentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(42, 42, 42)
                        .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_CrearCuentaLayout.createSequentialGroup()
                                .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5))
                            .addComponent(tf_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(tf_username)
                            .addComponent(tf_nombre)))
                    .addGroup(jd_CrearCuentaLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_CrearCuentaLayout.setVerticalGroup(
            jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearCuentaLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel6)
                .addGap(52, 52, 52)
                .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(36, 36, 36)
                .addGroup(jd_CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(bt_crearCuenta)
                .addGap(57, 57, 57))
        );

        jLabel7.setText("Username");

        jLabel8.setText("Contraseña");

        tf_usernameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameLoginActionPerformed(evt);
            }
        });

        bt_login.setText("Ingresar");
        bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_loginMouseClicked(evt);
            }
        });

        jLabel9.setText("Log In");

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(53, 53, 53)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_usernameLogin)
                            .addComponent(tf_password, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(bt_login))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel9)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addGap(54, 54, 54)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_usernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(bt_login)
                .addGap(38, 38, 38))
        );

        bt_usuarios.setText("Usuarios");
        bt_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_usuariosMouseClicked(evt);
            }
        });

        bt_canciones.setText("Canciones");
        bt_canciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cancionesMouseClicked(evt);
            }
        });

        bt_albums.setText("Albums");
        bt_albums.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_albumsMouseClicked(evt);
            }
        });

        bt_guardarUsuarios.setText("Guardar Usuarios");

        jLabel17.setText("Menu Principal");

        jMenu3.setText("Opciones");

        jMenuItem1.setText("Explorar");
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Crear PlayList");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Ver PlayList");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Ver Favoritos");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Salir");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jd_menu.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jd_menuLayout = new javax.swing.GroupLayout(jd_menu.getContentPane());
        jd_menu.getContentPane().setLayout(jd_menuLayout);
        jd_menuLayout.setHorizontalGroup(
            jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuLayout.createSequentialGroup()
                .addGroup(jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_menuLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_guardarUsuarios)
                            .addComponent(bt_albums)
                            .addComponent(bt_canciones)
                            .addComponent(bt_usuarios)))
                    .addGroup(jd_menuLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel17)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jd_menuLayout.setVerticalGroup(
            jd_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel17)
                .addGap(43, 43, 43)
                .addComponent(bt_usuarios)
                .addGap(38, 38, 38)
                .addComponent(bt_canciones)
                .addGap(46, 46, 46)
                .addComponent(bt_albums)
                .addGap(52, 52, 52)
                .addComponent(bt_guardarUsuarios)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jl_listarUsuarios);

        jLabel10.setText("Lista de Usuarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel10)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar", jPanel1);

        jScrollPane2.setViewportView(jl_eliminarUsuarios);

        bt_eliminar.setText("Eliminar");

        jLabel11.setText("Usuarios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(bt_eliminar))
                    .addComponent(jLabel11))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_eliminar)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Eliminar", jPanel2);

        javax.swing.GroupLayout jd_usuariosLayout = new javax.swing.GroupLayout(jd_usuarios.getContentPane());
        jd_usuarios.getContentPane().setLayout(jd_usuariosLayout);
        jd_usuariosLayout.setHorizontalGroup(
            jd_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jd_usuariosLayout.setVerticalGroup(
            jd_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jLabel14.setText("Nombre Cancion");

        jLabel15.setText("Genero");

        jLabel18.setText("Artista");

        jLabel19.setText("Duración");

        jLabel20.setText("Albums");

        sp_duracion.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel21.setText("Segundos");

        bt_crearCancion.setText("Crear");

        jLabel22.setText("Crear Canción");

        javax.swing.GroupLayout jd_CancionesLayout = new javax.swing.GroupLayout(jd_Canciones.getContentPane());
        jd_Canciones.getContentPane().setLayout(jd_CancionesLayout);
        jd_CancionesLayout.setHorizontalGroup(
            jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CancionesLayout.createSequentialGroup()
                .addGroup(jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CancionesLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18))
                        .addGap(36, 36, 36)
                        .addGroup(jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_CancionesLayout.createSequentialGroup()
                                .addComponent(sp_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21))
                            .addComponent(tf_nombreCancion)
                            .addComponent(tf_genero)
                            .addComponent(tf_artistaCancion, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(cb_albums, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_CancionesLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(bt_crearCancion)))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CancionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(171, 171, 171))
        );
        jd_CancionesLayout.setVerticalGroup(
            jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CancionesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel22)
                .addGap(64, 64, 64)
                .addGroup(jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_nombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_artistaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(sp_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(37, 37, 37)
                .addGroup(jd_CancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cb_albums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(bt_crearCancion)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel23.setText("Nombre Album");

        jLabel24.setText("Artista");

        bt_crearAlbum.setText("jButton1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nombreAlbum)
                    .addComponent(tf_artistaAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(bt_crearAlbum)
                .addGap(161, 161, 161))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tf_nombreAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tf_artistaAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(bt_crearAlbum)
                .addGap(79, 79, 79))
        );

        jTabbedPane2.addTab("Crear Album", jPanel3);

        jLabel12.setText("Albums");

        jt_listarAlbums.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Album", "Canción", "Artista", "Duración"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jt_listarAlbums);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jTabbedPane2.addTab("Listar Albums", jPanel4);

        jScrollPane3.setViewportView(jl_eliminarAlbums);

        jLabel13.setText("Albums");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        jTabbedPane2.addTab("Eliminar Albums", jPanel5);

        javax.swing.GroupLayout jd_albumsLayout = new javax.swing.GroupLayout(jd_albums.getContentPane());
        jd_albums.getContentPane().setLayout(jd_albumsLayout);
        jd_albumsLayout.setHorizontalGroup(
            jd_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jd_albumsLayout.setVerticalGroup(
            jd_albumsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_CrearCuenta.setText("Crear Cuenta");
        jl_CrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_CrearCuentaMouseClicked(evt);
            }
        });

        jl_login.setText("Log In");
        jl_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_loginMouseClicked(evt);
            }
        });

        jLabel16.setText("Cargar Usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jl_login)
                    .addComponent(jl_CrearCuenta))
                .addContainerGap(387, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jl_CrearCuenta)
                .addGap(71, 71, 71)
                .addComponent(jl_login)
                .addGap(57, 57, 57)
                .addComponent(jLabel16)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jl_CrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_CrearCuentaMouseClicked
        jd_CrearCuenta.pack();
        jd_CrearCuenta.setModal(true);
        jd_CrearCuenta.setVisible(true);
        jd_CrearCuenta.setLocationRelativeTo(this);
    }//GEN-LAST:event_jl_CrearCuentaMouseClicked

    private void jl_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_loginMouseClicked
        jd_login.pack();
        jd_login.setModal(true);
        jd_login.setVisible(true);
        jd_login.setLocationRelativeTo(this);
    }//GEN-LAST:event_jl_loginMouseClicked

    private void bt_crearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearCuentaMouseClicked
        Usuarios u = new Usuarios(tf_nombre.getText(), tf_username.getText(), tf_contraseña.getText(), (Integer) sp_edad.getValue());
        users.add(u);
        
        tf_nombre.setText("");
        tf_username.setText("");
        tf_contraseña.setText("");
        sp_edad.setValue(14);
    }//GEN-LAST:event_bt_crearCuentaMouseClicked

    private void bt_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseClicked
        if (users.isEmpty()) {
            JOptionPane.showMessageDialog(jd_login, "No hay Ningun Usuario creado");
        }
        UsuarioAct=tf_usernameLogin.getText();
        for (int i = 0; i < users.size(); i++) {
            if ((users.get(i).getUsername().equals(UsuarioAct)) && users.get(i).getPassword().equals(tf_password)) {
                jd_menu.pack();
                jd_menu.setModal(true);
                jd_menu.setVisible(true);
                jd_menu.setLocationRelativeTo(this);
            }else{
                
            }
        }
        
    }//GEN-LAST:event_bt_loginMouseClicked

    private void tf_usernameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameLoginActionPerformed
        
    }//GEN-LAST:event_tf_usernameLoginActionPerformed

    private void bt_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_usuariosMouseClicked
        jd_usuarios.pack();
        jd_usuarios.setModal(true);
        jd_usuarios.setVisible(true);
        jd_usuarios.setLocationRelativeTo(this);
    }//GEN-LAST:event_bt_usuariosMouseClicked

    private void bt_cancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cancionesMouseClicked
        jd_Canciones.pack();
        jd_Canciones.setModal(true);
        jd_Canciones.setVisible(true);
        jd_Canciones.setLocationRelativeTo(this);
    }//GEN-LAST:event_bt_cancionesMouseClicked

    private void bt_albumsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_albumsMouseClicked
        jd_albums.pack();
        jd_albums.setModal(true);
        jd_albums.setVisible(true);
        jd_albums.setLocationRelativeTo(this);
    }//GEN-LAST:event_bt_albumsMouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_albums;
    private javax.swing.JLabel bt_canciones;
    private javax.swing.JButton bt_crearAlbum;
    private javax.swing.JButton bt_crearCancion;
    private javax.swing.JButton bt_crearCuenta;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JLabel bt_guardarUsuarios;
    private javax.swing.JButton bt_login;
    private javax.swing.JLabel bt_usuarios;
    private javax.swing.JComboBox<String> cb_albums;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JDialog jd_Canciones;
    private javax.swing.JDialog jd_CrearCuenta;
    private javax.swing.JDialog jd_albums;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_menu;
    private javax.swing.JDialog jd_usuarios;
    private javax.swing.JLabel jl_CrearCuenta;
    private javax.swing.JList<String> jl_eliminarAlbums;
    private javax.swing.JList<String> jl_eliminarUsuarios;
    private javax.swing.JList<String> jl_listarUsuarios;
    private javax.swing.JLabel jl_login;
    private javax.swing.JTable jt_listarAlbums;
    private javax.swing.JSpinner sp_duracion;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JTextField tf_artistaAlbum;
    private javax.swing.JTextField tf_artistaCancion;
    private javax.swing.JPasswordField tf_contraseña;
    private javax.swing.JTextField tf_genero;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombreAlbum;
    private javax.swing.JTextField tf_nombreCancion;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_username;
    private javax.swing.JTextField tf_usernameLogin;
    // End of variables declaration//GEN-END:variables
    ArrayList<Usuarios> users = new ArrayList();
    String UsuarioAct;
    ArrayList<Albums> albums = new ArrayList();
    ArrayList<Canciones> canciones = new ArrayList();
}
